- source/includes/_api_types.md
- source/index.md
EEN timestamp is kicking it off
> add types section

- source/includes/_api_account.md
- source/includes/_api_layout.md
Update the account model to reflect new fields. Update layouts to match new format. Recording and search sections need same treatment.
> update account and layouts sections. Recording and search sections todo

- source/includes/_api_account.md
- source/includes/_errors.md
[API-236] Create Account error code update to reflect API behavior
> [API-236] Create Account error code update to reflect API behavior

- source/includes/_api_authentication.md
[API-237] Fix for curl request data handling to force data through as json content
> [API-237] Fix for curl request data handling

- source/includes/_api_aaa.md
- source/includes/_errors.md
[API-235] Logout error code update following fix implemented in API-211
> [API-235] Logout error code update following fix implemented in API-211

- source/includes/_sample_code.md
Added a html link with "open in new window" behavior to an existing EEN tutorial article
> [EEN-8006] Added a html link with "open in new window" behavior to an existing EEN tutorial article

- source/includes/_sample_code.md
- source/javascripts/app/_modal.js
Removal of outdated flash player related example code.
> [EEN-8262] Removal of obsolete example code

- source/includes/_api_user.md
Extended the description for list users to include search by email
> [EEN-8010] Added description for list users search by email

- source/includes/_api_notice.md
Just a quick update, mostly about switch between default EEN TOS and custom TOS.
What has changed:
> [EEN-9184] Terms of Service, update.

- source/includes/_api_managed_switch.md
After releasing: https://github.com/EENCloud/videobank/pull/1808 update of docs will be needed.
End point:
/g/manage_switch
Parameters to update:
* **_guid_** to **_switch_guid_**
* **_bridge_** to **_bridge_id_**
> [EEN-10796] Update parameters in /manage_switch endpoint.

- source/includes/_api_aaa.md
- source/includes/_api_account.md
- source/includes/_api_action.md
- source/includes/_api_annotation.md
- source/includes/_api_asset.md
- source/includes/_api_authentication.md
- source/includes/_api_bridge.md
- source/includes/_api_camera.md
- source/includes/_api_feedback.md
- source/includes/_api_layout.md
- source/includes/_api_managed_switch.md
- source/includes/_api_metric.md
- source/includes/_api_notice.md
- source/includes/_api_pngspan.md
- source/includes/_api_poll.md
- source/includes/_api_search.md
- source/includes/_api_user.md
- source/includes/_introduction.md
- source/includes/_kittens.md
- source/includes/_sample_code.md
... also remove second colon from: `Authentication: [API_KEY]:`
> [NOTRACKER] Update arguments in annt/list cURL snippet.

- source/includes/_api_asset.md
Jira: https://eagleeyenetworks.atlassian.net/browse/EEN-7118
Screenshot: 
I think there's no precedent for some things like I'm describing, like specifying video format without a parameter. I improvised but also tried to make it fit well with the rest. Also, I have doubts about where to put the bits about -o and -O.
> [EEN-7118] Described 202 Pending behavior for asset/play/video

- source/includes/_api_asset.md
Preparing the prefetch sections for upcoming changes.
> added warnings for APIs being changed

- source/includes/_api_asset.md
Removed Prefect Image call because it is still being tested and I am still unsure that is generally needed.
> Updating documentation to match updated Prefetch Video call

- source/includes/_api_bridge.md
- source/includes/_api_camera.md
Add all missing device types to enum lists.
> [EEN-13877] Update Device Type Enums

- source/includes/_api_aaa.md
- source/includes/_api_account.md
Update:
- Account settings
- AAA SSO section
> [EEN-14247] Update SSO descriptions.

- source/includes/_api_aaa.md
- source/includes/_api_authentication.md
> [EEN-15432] Add missing error code for invalid IP

- source/includes/_api_asset.md
Add description of the Snapshot api to retrieve a full resolution image for a camera.
> EEN-20586 Add Snapshot API doc

- chart/api-docs/templates/ingress.yaml
Signed-off-by: Aaron Layfield <aaron.layfield@gmail.com>
> Fixing Kubernetes deprecations

- source/includes/_api_aaa.md
- source/includes/_api_account.md
- source/includes/_api_action.md
- source/includes/_api_annotation.md
- source/includes/_api_asset.md
- source/includes/_api_authentication.md
- source/includes/_api_bridge.md
- source/includes/_api_camera.md
- source/includes/_api_feedback.md
- source/includes/_api_layout.md
- source/includes/_api_managed_switch.md
- source/includes/_api_metric.md
- source/includes/_api_notice.md
- source/includes/_api_pngspan.md
- source/includes/_api_poll.md
- source/includes/_api_search.md
- source/includes/_api_user.md
- source/includes/_sample_code.md
- updated example URLs to reflect usage of `active_brand_subdomain`
(red box is an illustration to what text was added, not actual part of release!)
> [EEPD-9926] Update Example URL

- .gitignore
- Dockerfile
- Gemfile
- Gemfile.lock
From ruby `2.6.5` to `3.1.3`.
https://apidocs.test-1045.eagleeyenetworks.com/
> [EEPD-20096] Bumping Base Image
